const DOCUMENT_LABELS: Record<string, string> = {
  rg_cpf: 'RG/CPF',
  comprovante_residencia: 'Comprovante de Residência',
  matricula: 'Matrícula',
  ccir: 'CCIR',
  itr: 'ITR',
  car: 'CAR',
  ibama: 'IBAMA',
  trabalho_escravo: 'Trabalho Escravo',
  debitos_federais: 'Débitos Federais',
  documento_divorcio: 'Documento de Divórcio',
  rg_cpf_conjuge: 'RG/CPF do Cônjuge',
  certidao_casamento: 'Certidão de Casamento',
  cpf: 'CPF',
  rg: 'RG',
  'certidao-nascimento': 'Certidão de Nascimento',
  'certidao-casamento': 'Certidão de Casamento',
  'certidao-obitos': 'Certidão de Óbito',
  iptu: 'IPTU',
  'registro-imovel': 'Registro do Imóvel',
  escritura: 'Escritura',
  'contrato-compra-venda': 'Contrato de Compra e Venda',
  procuracao: 'Procuração',
  'estatuto-casamento': 'Estatuto de Casamento',
  'pacto-antinupcial': 'Pacto Antinupcial',
  'certidao-conjuge': 'Certidão do Cônjuge',
  'comprovante-residencia': 'Comprovante de Residência',
  cnh: 'CNH',
  dda_existente: 'DDA Existente',
  dda_distribuida: 'DDA Distribuída',
  certidao_matricula: 'Certidão de Matrícula',
  licenca_ambiental: 'Licença Ambiental',
  escritura_compra_venda: 'Escritura de Compra e Venda',
  certidao_onus_reais: 'Certidão de Ônus Reais',
  cnd_federal: 'CND Federal',
  cnd_estadual: 'CND Estadual',
  cnd_municipal: 'CND Municipal',
  certidao_fracao_ideal: 'Certidão de Fração Ideal',
}

export function getDocumentLabel(key: string): string {
  if (DOCUMENT_LABELS[key]) return DOCUMENT_LABELS[key]
  return key.replace(/[-_]/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase())
}
