import { KanbanColumnType, KanbanCardType } from '@/types/kanban'

export const MOCK_COLUMNS: KanbanColumnType[] = [
  { id: 'assinatura', title: 'Assinatura da carta proposta' },
  { id: 'doc_basica', title: 'Aguardando documentação básica' },
  { id: 'certidoes', title: 'Emissão das certidões' },
  { id: 'escritorio', title: 'Distribuída ao escritório externo' },
  { id: 'dda', title: 'DDA' },
  { id: 'dd_preliminar', title: 'Análise interna DD preliminar' },
  { id: 'dd_conclusiva', title: 'DD conclusiva' },
  { id: 'analise_conclusiva', title: 'Análise interna DD conclusiva' },
]

export const MOCK_CARDS: KanbanCardType[] = [
  {
    id: 'c1',
    title: 'Fazenda Esperança',
    location: { city: 'Alta Floresta', state: 'MT' },
    owner: 'João de Deus Silva',
    area: 1250,
    status: 'info',
    statusText: 'Em andamento',
    responsible: 'Ana Costa',
    stageId: 'assinatura',
  },
  {
    id: 'c2',
    title: 'Sítio Alvorada',
    location: { city: 'São Félix do Xingu', state: 'PA' },
    owner: 'Maria Oliveira Santos',
    area: 450,
    status: 'alert',
    statusText: 'Aguardando CAR',
    responsible: 'Carlos Mendes',
    stageId: 'doc_basica',
  },
  {
    id: 'c3',
    title: 'Estância Nova',
    location: { city: 'Porto Velho', state: 'RO' },
    owner: 'Roberto Almeida',
    area: 3200,
    status: 'info',
    statusText: 'Certidões solicitadas',
    responsible: 'Ana Costa',
    stageId: 'certidoes',
  },
  {
    id: 'c4',
    title: 'Vale Verde',
    location: { city: 'Marabá', state: 'PA' },
    owner: 'Investimentos Agro S.A.',
    area: 890,
    status: 'critical',
    statusText: 'Pendência Jurídica',
    responsible: 'Fernanda Lima',
    stageId: 'escritorio',
  },
  {
    id: 'c5',
    title: 'Fazenda Rio Limpo',
    location: { city: 'Cuiabá', state: 'MT' },
    owner: 'Pedro Nogueira',
    area: 1500,
    status: 'info',
    statusText: 'Análise DDA iniciada',
    responsible: 'Carlos Mendes',
    stageId: 'dda',
  },
]
