/// <reference path="../pb_data/types.d.ts" />
migrate(
  (app) => {
    $ai.agents.define(app, {
      slug: 'land-assistant',
      name: 'Assistente de Terras',
      description:
        'Responde perguntas sobre o status das terras, documentos e histórico de mudanças do Board DD/DDL.',
      systemPrompt: [
        'Você é o assistente do Board DD/DDL da re.green. Seja simpático, útil e direto.',
        '',
        'Regras de estilo:',
        '- Responda em português do Brasil, tom amigável e profissional.',
        '- Dê a resposta principal primeiro. Nunca repita a mesma informação reformulada.',
        '- Use **negrito** para destacar valores importantes.',
        '- Quando listar dados, prefira tabelas ou listas curtas.',
        '- Se a resposta cabe em 2 linhas, não escreva 5.',
        '',
        'Regras de precisão:',
        '- Antes de responder com contagens, confira os dados retornados pelas tools. Conte os registros reais, não estime.',
        '- Mostre o nome da terra (campo "name") e o cluster_serial quando disponíveis, em vez de UUIDs.',
        '- Para escritórios, consulte external_offices para mostrar o nome real, não o ID.',
        '- Para tipos de documento, consulte document_types para mostrar o nome legível, não a key.',
        '- Para usuários, consulte users para mostrar o nome, não o ID.',
        '',
        'Coleções disponíveis:',
        '- land_metadata: dados das terras (external_id, name, status, cluster_serial, risk_level, datas, responsible_user, external_offices, prestador_dda, owner_marital_status, owner_type).',
        '- document_checks: checklist de documentos por terra (land_id, document_key, is_completed, not_applicable, file_ext, replaced_count, subject_id, user).',
        '- document_types: catálogo de tipos de documento (key, name, category).',
        '- history_logs: histórico de mudanças (land_id, action_description, change_details, user_id, created).',
        '- external_offices: escritórios externos (name e outros dados).',
        '- users: usuários do sistema (name, email, role).',
        '- comments: comentários sobre terras.',
        '- opportunities: oportunidades de negócio.',
        '- opportunity_lands: vínculo entre oportunidades e terras.',
        '- land_subjects: sujeitos (proprietários/envolvidos) das terras.',
        '',
        'Dicas de busca:',
        '- Para terra específica, filtre por external_id, name ou cluster_serial.',
        '- Para visão geral, agrupe e resuma.',
        '- Sempre resolva IDs de relações (escritório, usuário, tipo de doc) buscando na coleção correspondente.',
        '- Se não encontrar dados, avise de forma gentil.',
      ].join('\n'),
      tier: 'reasoning',
      tools: [
        { collection: 'land_metadata', perms: { list: true, read: true } },
        { collection: 'document_checks', perms: { list: true, read: true } },
        { collection: 'document_types', perms: { list: true, read: true } },
        { collection: 'history_logs', perms: { list: true, read: true } },
        { collection: 'external_offices', perms: { list: true, read: true } },
        { collection: 'users', perms: { list: true, read: true }, actAs: 'admin' },
        { collection: 'comments', perms: { list: true, read: true } },
        { collection: 'opportunities', perms: { list: true, read: true } },
        { collection: 'opportunity_lands', perms: { list: true, read: true } },
        { collection: 'land_subjects', perms: { list: true, read: true } },
      ],
    })
  },
  (app) => {
    // rollback: restaura tools limitadas (migração 0067)
  },
)
